apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: qudwndh/nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVER_NAME
          value: "localhost"
        - name: WEB_SERVICE_HOST
          value: "web"
        - name: WEB_SERVICE_PORT
          value: "5000"
